version: '3'

networks:
  application:
    driver: bridge

services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./codigo/:/var/www/html/
    ports:
      - '9000:9000'
    networks:
      - application
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./codigo/:/var/www/html/
    ports:
      - '80:80'
    networks:
      - application
  mysql:
    container_name: banco_mysql
    image: mysql:5
    networks:
      - application
    volumes:
      - ./mysql_vol:/var/lib/mysql
    env_file:
      - ./mysql/mysql.env
    ports:
      - '3306:3306'